---
title: "CPPI Optimization"
author: "Nikolaj Andreasen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=10, fig.height=5)
```

# Pakker
```{r}
library(tidyverse)
library(frenchdata)
library(ggplot2)
library(quadprog)
library(lubridate)
library(lpSolve)
library(xtable)
```

# Loading data
```{r message=FALSE}
data_sets = get_french_data_list() # All the datasets in the package


# US stocks
# Nr 1 er månedlige returns
# Nr 2 er årlige returns
ff_3_factors <- download_french_data("Fama/French 3 Factors") # Download of data
# f_3_factors$subsets$data[[2]] # How to extract dataset
# browse_details_page(ff_3_factors) # Details of the dataset


size_mom_6 <- download_french_data("6 Portfolios Formed on Size and Momentum (2 x 3)")
size_mom_25 <- download_french_data("25 Portfolios Formed on Size and Momentum (5 x 5)")

# EU stocks in US dollars
size_mom_6_euro <- download_french_data("6 European Portfolios Formed on Size and Momentum (2 x 3)")
size_mom_25_euro <- download_french_data("25 European Portfolios Formed on Size and Momentum (5 x 5)")

# Other
exchange_rate <- read_csv("Data AA/eurofxref-hist.csv")

Exchange_rate_US <- exchange_rate %>% 
  filter(Date >= "2004-09-01", Date <= "2025-08-31") %>% 
  select(c("Date", "USD"))
Exchange_rate_US <- Exchange_rate_US[nrow(Exchange_rate_US):1,]

Exchange_rate_US <- Exchange_rate_US %>% 
  mutate(Date = floor_date(Date, " month")) %>% 
  group_by(Date) %>% 
  summarise(USD = mean(USD))

RF.EU <- read_rds("All_years_ready.rds")
RF.EU <- select(RF.EU, c("TIME_PERIOD", "return"))

factors <- read_rds("new_factors_all.rds")

returns_choice <- readRDS("returns_choice.rds")
All_years <- readRDS("All_years_ready.rds") # The beta values
```


# Prerequisit
```{r}
EUR_USD <- exchange_rate %>%
  filter(as.Date(Date) >= as.Date("2004-08-01")) %>%
  select(Date, USD) %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(year = year(Date), month = month(Date)) %>%
  slice_max(Date, n = 1) %>%   # last date in each month
  ungroup() %>%
  arrange(Date)
EUR_USD <- EUR_USD[1:253,]
EUR_USD$return <- lag(EUR_USD$USD)/EUR_USD$USD-1
EUR_USD <- EUR_USD[2:253,]

avg_vw_returns_euro <- size_mom_6_euro$subsets$data[[1]] %>% filter(date >= 200409)
number_firms_euro <- size_mom_6_euro$subsets$data[[5]] %>% filter(date >= 200409)
avg_market_cap_euro <- size_mom_6_euro$subsets$data[[6]] %>% filter(date >= 200409)

total_values_euro <- number_firms_euro[,-1] * avg_market_cap_euro[,-1]
total_market_value_euro <- rowSums(total_values_euro)

avg_vw_returns_euro_eur <- ((1 + avg_vw_returns_euro[,-1]/100) * (1 + EUR_USD$return) - 1) * 100

MKT_EU_EU <- data.frame(
  date = number_firms_euro$date,  
  Mkt  = rowSums(avg_vw_returns_euro_eur * total_values_euro) /
         total_market_value_euro)
```

# CPPI
## CPPI Function
```{r}
TTM <-  seq(10, 0, -1/12)

CPPI <- function(m,L_target,L_trigger,return_series){
  Guarantees <- c()
  Floor_month <- array(NA, c(120+1, length(36:124)))
  C_month <- array(NA, c(120+1, length(36:124)))
  E_month <- array(NA, c(120+1, length(36:124)))
  W_month <- array(NA, c(120+1, length(36:124)))
  Trigger_hit <- array(NA, c(120, length(36:124)))
  N_month <- array(NA, c(120+1, length(36:124)))
for (j in 36:124){
  # ZCB_prices <-  All_years[j:(j+120),] %>% 
  #   mutate(
  #   TTM = TTM,
  #   z = BETA0 +
  #     BETA1 * ((1 - exp(-TTM / TAU1)) / (TTM / TAU1)) +
  #     BETA2 * ((1 - exp(-TTM / TAU1)) / (TTM / TAU1) - exp(-TTM / TAU1)) +
  #     BETA3 * ((1 - exp(-TTM / TAU2)) / (TTM / TAU2) - exp(-TTM / TAU2)),
  #   P_T = exp(-z/100 * TTM))
  # ZCB_prices$P_T[121] <- 1
  
  window_data <- All_years[j:(j + 120), ]
  ZCB_prices <- window_data$BETA0 +
         window_data$BETA1 * ((1 - exp(-TTM / window_data$TAU1)) / (TTM / window_data$TAU1)) +
         window_data$BETA2 * (((1 - exp(-TTM / window_data$TAU1)) / (TTM / window_data$TAU1)) - exp(-TTM / window_data$TAU1)) +
         window_data$BETA3 * (((1 - exp(-TTM / window_data$TAU2)) / (TTM / window_data$TAU2)) - exp(-TTM / window_data$TAU2))

    P_T <- exp(-ZCB_prices/100 * TTM)
    P_T[121] <- 1 # Manually set the final price to 1.
  
  E_returns <- (return_series %>% filter(ym(date) >= All_years$TIME_PERIOD[j]))$return/100
  
  W <- 100
  W_month[1, j-35] <- W
  Floor <- W/L_target
  Floor_month[1,j-35] <- Floor
  C <- W-Floor
  C_month[1,j-35] <- C
  E <- max(min(m*C,W),0)
  E_month[1, j-35] <- E
  A <- E
  etaR <- (W-E)/P_T[1]
  N <- Floor/P_T[1]
  N_month[,j-35] <- N
  for (i in 1:120){
    A <- (1+E_returns[i])*A
    R <- etaR*P_T[i+1]
    W <- A+R
    W_month[i+1, j-35] <- W
    Floor <- N*P_T[i+1]
    Floor_month[i+1, j-35] <- Floor
    C <- W-Floor
    C_month[i+1, j-35] <- C
    E <- max(min(m*C,W),0)
    E_month[i+1, j-35] <- E
    A <- E
    etaR <- (W-E)/P_T[i+1]
    
    if (W/Floor > L_trigger){
      N <- W/(L_target*P_T[i+1])
      Trigger_hit[i, j-35] <- 1
    }else{
      Trigger_hit[i, j-35] <- 0
    }
    N_month[i,j-35] <- N
  }
  Guarantees[j-35] <- W
}
  return(list("Guarantee" = Guarantees, "Floor" = Floor_month, "C" = C_month, "Wealth_month" = W_month, "E" = E_month, "Trigger_hit" = Trigger_hit, "Guarantee_month" = N_month))
}
```

## Base case
```{r}
m <- 1
L_target <- 125/100
L_trigger <- 130/100
returns_choice <- readRDS("returns_choice.rds")
mkt_EU_period <- MKT_EU_EU %>% filter(date >= 200709 & date <= 202412)
colnames(mkt_EU_period) <- c("date", "return")

# Calculating CPPI
guarantees_choice <- CPPI(m, L_target, L_trigger, returns_choice)
guarantees_EU_equity <- CPPI(m, L_target, L_trigger, mkt_EU_period)

guarantee_df <- data.frame(date = All_years$TIME_PERIOD[36:124],
                           "Portfolio 1" = guarantees_choice$Guarantee,
                           "European Equity" = guarantees_EU_equity$Guarantee)

guarantee_df %>% 
  pivot_longer(cols = -date, names_to = "Portfolio", values_to = "Guarantee") %>% 
  ggplot(aes(x = as.Date(date), y = Guarantee, color = Portfolio)) +
    geom_line(size = 1.1) +
    geom_point(size = 2, alpha = 0.7) +
    # geom_line(color = "#0072B2", size = 1.1) +
    # geom_point(color = "#0072B2", size = 2, alpha = 0.7) +
    scale_color_manual(values = c("Portfolio.1" = "#0072B2", "European.Equity" = "#D55E00"),
                       breaks=c("Portfolio.1", "European.Equity"),
                       labels=c("Portfolio 1", "European Equity")) +
    scale_x_date(date_labels = "%Y", date_breaks = "2 years") +
    scale_y_continuous(labels = scales::number_format(accuracy = 0.01)) +
    labs(
      title = "Development of the Portfolio Guarantee Over Time",
      subtitle = "Guarantee level implied by CPPI floor mechanism",
      x = "Date",
      y = "Guarantee Value"
    ) +
    theme_minimal(base_size = 13) +
    theme(
      plot.title = element_text(face = "bold", size = 15, hjust = 0.5),
      plot.subtitle = element_text(size = 11, hjust = 0.5, color = "gray40"),
      axis.title = element_text(face = "bold"),
      panel.grid.minor = element_blank(),
      panel.grid.major.x = element_blank()
    )
```

## Optimal variables
```{r, fig.width=10, fig.height=5}
# searchspace
m <- seq(1, 20, 0.5)
L_target <- seq(105, 200, 5)/100
L_trigger <- seq(110, 230, 5)/100
search_grid = expand.grid(m = m, "L_target" = L_target, "L_trigger" = L_trigger) %>%
  filter(L_target < L_trigger & L_trigger - L_target <= 0.3)
search_grid <- sort_by(search_grid, ~list(m, L_target, L_trigger))
new_names <- apply(search_grid, 1, paste, collapse = "x")


guarantees <- vector(mode = "list", length = nrow(search_grid))
for(i in 1:nrow(search_grid)){
  guarantees[[i]] <- CPPI(search_grid[i,1], search_grid[i,2], search_grid[i,3], returns_choice)
}
names(guarantees) <- new_names

# Loading guarantees
# guarantees <- readRDS("C:/Users/Nikolaj/OneDrive - University of Copenhagen/Aktuar/5. år/Asset allocation/Exam project/CPPI_strats.rds")

# guarantees <- readRDS("C:/Users/nikol/OneDrive - University of Copenhagen/Aktuar/5. år/Asset allocation/Exam project/CPPI_strats.rds")
```

### m
```{r}
B <- map(guarantees, "C")
K <- map(guarantees, "Guarantee_end")

# Rækker er start på periode
# Søjler er parameter kombination
# short_fall er andelen af alle perioder, hvor man falder under floor
short_fall <- array(NA, dim = c(ncol(B[[1]]), length(B)))
guarantees_min <- rep(NA, length(K))


for(i in 1:length(B)){
  short_fall[,i] <- (colSums(B[[i]] <= 0) > 0)
}

check_m <- paste(m, "x", sep = "")
k <- length(which(startsWith(new_names, check_m[1])))
indices_m <- array(NA, c(k, length(m)))
for(i in 1:length(m)){
  indices_m[,i] <- which(startsWith(new_names, check_m[i]))
}

A <- colMeans(short_fall)

short_fall_df <- matrix(A[indices_m], nrow = nrow(indices_m), ncol = ncol(indices_m), byrow = FALSE)
short_fall_df <- as.tibble(short_fall_df)

guarantees_m_df <- matrix(K[indices_m], nrow = nrow(indices_m), ncol = ncol(indices_m), byrow = FALSE)
guarantees_m_df <- as.tibble(guarantees_m_df)

colnames(short_fall_df) <- m
colnames(guarantees_m_df) <- m
guarantees_m_plot_df <- guarantees_m_df %>% 
  pivot_longer(cols = everything(), names_to = "m", values_to = "Guarantee") %>% 
  group_by(m) %>% 
  summarise("Mean_guarantee" = mean(Guarantee))

# short_fall_df %>% 
#   pivot_longer(cols = everything(), names_to = "m", values_to = "Short_fall_prop") %>%
#   group_by(m) %>% 
#   summarise(short_fall_prop_m = mean(Short_fall_prop)) %>% 
#   arrange(as.numeric(m)) %>% 
#   left_join(guarantees_m_plot_df, by = "m") %>% 
#   ggplot(aes(as.numeric(m), short_fall_prop_m)) +
#     geom_point() 

# 1. Create the detailed 'min_df' dataframe
min_df <- K %>%
  imap_dfr(~ {
    # .y is the name (e.g., "7x1.25x1.3"), .x is the vector
    parts <- str_split(.y, "x", simplify = TRUE)
    
    tibble(
      m = parts[1],
      Target = parts[2],
      Trigger = parts[3],
      min_value = min(.x)
    )
  })

# 2. Group and summarize (this code is the same as before)
mean_of_mins_df <- min_df %>%
  group_by(m) %>%
  summarize(
    mean_of_mins = mean(min_value)
  ) %>%
  mutate(m = as.numeric(m)) %>%
  arrange(m)


# Shortfall and minimum guarantee
df_cleaned <- short_fall_df %>% 
  pivot_longer(cols = everything(), names_to = "m", values_to = "Short_fall_prop") %>%
  group_by(m) %>% 
  summarise(short_fall_prop_m = mean(Short_fall_prop)) %>% 
  arrange(as.numeric(m)) %>% 
  cbind(mean_of_mins_df$mean_of_mins) %>%
  rename(mean_of_mins = `mean_of_mins_df$mean_of_mins`) %>%
  mutate(m = as.numeric(m))

scale_factor <- max(df_cleaned$short_fall_prop_m) / max(df_cleaned$mean_of_mins)

ggplot(df_cleaned, aes(x = m)) +
  
  geom_line(aes(y = short_fall_prop_m, color = "Shortfall Probability"), size = 1.2) +
  geom_point(aes(y = short_fall_prop_m), color = "#0072B2", size = 2.5) +
  
  geom_line(aes(y = mean_of_mins * scale_factor, color = "Minimum guarantee"), size = 1.2) +
  geom_point(aes(y = mean_of_mins * scale_factor), color = "#D55E00", size = 2.5) +
  
  scale_y_continuous(
    name = "Shortfall Probability",
    labels = scales::percent_format(accuracy = 0.01),
    sec.axis = sec_axis(
      trans = ~ . / scale_factor,
      name = "Minimum guarantee"
    )
  ) +
  scale_x_continuous(breaks = seq(1, 20, by = 2)) +
  scale_color_manual(
    name = "",
    values = c("Shortfall Probability" = "#0072B2", "Minimum guarantee" = "#D55E00")
  ) +
  
  labs(
    title = "Shortfall Probability and minimum guarantee",
    x = "Multiplier (m)"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    # legend.position = c(0.95, 0.05),
    # legend.justification = c("right", "bottom"),
    # legend.background = element_rect(fill = "white", color = "grey80"),
    legend.title = element_text(face = "bold", size = 15),
    plot.title = element_text(size = rel(1.1), face = "bold"),
    legend.margin = margin(t = -10, r = 0, b = 0, l = 0, unit = "pt"),
    axis.title.x = element_text(face = "bold", size = 11),
    axis.title.y = element_text(face = "bold", size = 11)
    
  )
```

### Target level
#### safety rating and minimum initial guarantee
```{r}
guarantees_m_2.5 <- readRDS("C:/Users/Nikolaj/OneDrive - University of Copenhagen/Aktuar/5. år/Asset allocation/Exam project/CPPI_strats_m_2.5")
g_initial <- map(guarantees_m_2.5, "Guarantee_month")

initial_guarantee <- map_dfc(g_initial, ~ .[1,])

target_vals <- seq(1.05, 2.05, 0.1)
trigger_vals <- c("1.15", "1.3", "1.4", "1.95")

initial_guarantee %>%
  mutate(Period = row_number()) %>%
  
  pivot_longer(
    cols = -Period,
    names_to = "Name",
    values_to = "Value"
  ) %>%
  
  mutate(
    Target = str_split(Name, "x", simplify = TRUE)[, 2],
    Trigger = str_split(Name, "x", simplify = TRUE)[, 3]
  ) %>%
  
  filter(Target %in% target_vals) %>% 
  group_by(Target, Period) %>% 
  summarise("Value" = mean(Value)) %>% 
  ggplot(aes(x = Period, y = Value, color = Target)) +
  geom_line(size = 1.2) +
  geom_point(size = 2.5) +
  labs(
    title = "Initial Guarantee",
    x = "Start date of TDF",
    y = "Initial Guarantee",
    color = "Target"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")


initial_guarantee %>%
  mutate(Period = row_number()) %>%
  
  pivot_longer(
    cols = -Period,
    names_to = "Name",
    values_to = "Value"
  ) %>%
  
  mutate(
    Target = str_split(Name, "x", simplify = TRUE)[, 2],
    Trigger = str_split(Name, "x", simplify = TRUE)[, 3]
  ) %>%
  
  # filter(Target %in% target_vals) %>% 
  group_by(Target, Period) %>% 
  summarise("Value" = mean(Value)) %>% 
  mutate("initial_guarantee_over_100" = Value >= 100) %>% 
  group_by(Target) %>% 
  summarise("n_initial_over_100" = sum(initial_guarantee_over_100),
            "%_initial_over_100" = n_initial_over_100/89*100,
            "min_initial_guarantee" = min(Value)) %>% 
  View()
  
```


### Trigger level
#### Making dataframe
```{r}
m <- 2.5
L_target <- 1.27
L_trigger <- seq(128, 157, 1)/100
search_grid = expand.grid(m = m, "L_target" = L_target, "L_trigger" = L_trigger) %>%
  filter(L_target < L_trigger & L_trigger - L_target <= 0.3)
search_grid <- sort_by(search_grid, ~list(m, L_target, L_trigger))
new_names <- apply(search_grid, 1, paste, collapse = "x")

guarantees_trigger_target <- vector(mode = "list", length = nrow(search_grid))
for(i in 1:nrow(search_grid)){
  guarantees_trigger_target[[i]] <- CPPI(search_grid[i,1], search_grid[i,2], search_grid[i,3], returns_choice)
}
names(guarantees_trigger_target) <- new_names

wealth <- map(guarantees_trigger_target, "Wealth_month")
last_row_list <- lapply(wealth, function(x) x[nrow(x), ])
wealth_df <- tibble(date = All_years$TIME_PERIOD[36:124]) %>% 
  cbind(last_row_list)

df <- tibble(strings = new_names)

# 3. Use 'extract' to split the string into new columns
# "(\\d+)" is a regular expression for "one or more digits"
# 'convert = TRUE' automatically makes M, K, and L numeric
df_with_diff <- df %>%
  extract(strings, 
          into = c("m", "Target", "Trigger"), 
          # This regex now matches decimals
          "([\\d\\.]+)x([\\d\\.]+)x([\\d\\.]+)", 
          convert = TRUE) %>%
  mutate(Difference = Trigger - Target)

colnames(wealth_df) <- c("date", round(df_with_diff$Difference, 3))
```

#### plot of tie-ins
```{r Trigger hit}
Trigger_hit <- map(guarantees_trigger_target, "Trigger_hit")

Trigger_hit_df <- as.tibble(lapply(Trigger_hit, colSums))

summary_df <- Trigger_hit_df %>%
  summarise(across(everything(), median)) %>%
  
  pivot_longer(
    cols = everything(),
    names_to = "Name",
    values_to = "column_mean"
  ) %>%
  
  mutate(
    Trigger = str_split(Name, "x", simplify = TRUE)[, 3],
    Trigger = as.numeric(Trigger)
  )

ggplot(summary_df, aes(x = Trigger, y = column_mean)) +
  geom_line(size = 1.2, color = "#0072B2") +
  geom_point(size = 2.5, color = "#0072B2") +
  scale_x_continuous(breaks = seq(min(summary_df$Trigger), 
                                 max(summary_df$Trigger), 
                                 by = 0.05)) +
  scale_y_continuous(breaks = seq(min(0), 
                                 max(summary_df$column_mean), 
                                 by = 5)) +
  labs(
    title = "Median number of tie-ins by Trigger level",
    x = "Trigger Level",
    y = "Median number of tie-ins"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    # legend.position = c(0.95, 0.05),
    # legend.justification = c("right", "bottom"),
    # legend.background = element_rect(fill = "white", color = "grey80"),
    legend.title = element_text(face = "bold", size = 15),
    plot.title = element_text(size = rel(1.1), face = "bold"),
    legend.margin = margin(t = -10, r = 0, b = 0, l = 0, unit = "pt"),
    axis.title.x = element_text(face = "bold", size = 11),
    axis.title.y = element_text(face = "bold", size = 11)
    
  )
```

#### guarantees for trigger 132-136
```{r}
as_tibble(map(guarantees_trigger_target, "Guarantee")[paste("2.5x1.27x", seq(1.32, 1.36, 0.01), sep = "")]) %>% 
  rename_with(~ str_split_fixed(., "x", 3)[, 3]) %>% 
  cbind(tibble(date = 1:89)) %>% 
  pivot_longer(cols = -date, names_to = "Trigger_level", values_to = "Guarantee") %>% 
  ggplot(aes(date, Guarantee, color = Trigger_level)) +
    geom_line(linewidth = 0.8) +
    theme_minimal() +
    
    labs(color = "Trigger Level") + 
    
    theme(
      legend.position = c(0.98, 0.98),
      legend.justification = c("right", "top"),
      legend.background = element_rect(
        fill = "white", 
        color = "grey80"
      ),
      legend.title = element_text(face = "bold")
    )


```
