---
title: "CAPM model"
output: html_document
date: "2025-10-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  fig.width=10, fig.height=5
)
```

# Pakker
```{r}
library(tidyverse)
library(frenchdata)
library(ggplot2)
library(quadprog)
library(lubridate)
library(lpSolve)
library(xtable)
library(Rsolnp)
library(patchwork)
```

# Loading data
```{r message=FALSE}
data_sets = get_french_data_list() # All the datasets in the package


# US stocks
# Nr 1 er månedlige returns
# Nr 2 er årlige returns
ff_3_factors <- download_french_data("Fama/French 3 Factors") # Download of data
# f_3_factors$subsets$data[[2]] # How to extract dataset
# browse_details_page(ff_3_factors) # Details of the dataset


size_mom_6 <- download_french_data("6 Portfolios Formed on Size and Momentum (2 x 3)")
size_mom_25 <- download_french_data("25 Portfolios Formed on Size and Momentum (5 x 5)")

# EU stocks in US dollars
size_mom_6_euro <- download_french_data("6 European Portfolios Formed on Size and Momentum (2 x 3)")
size_mom_25_euro <- download_french_data("25 European Portfolios Formed on Size and Momentum (5 x 5)")

# Other
exchange_rate <- read_csv("Data AA/eurofxref-hist.csv")

Exchange_rate_US <- exchange_rate %>% 
  filter(Date >= "2004-09-01", Date <= "2025-08-31") %>% 
  select(c("Date", "USD"))
Exchange_rate_US <- Exchange_rate_US[nrow(Exchange_rate_US):1,]

Exchange_rate_US <- Exchange_rate_US %>% 
  mutate(Date = floor_date(Date, " month")) %>% 
  group_by(Date) %>% 
  summarise(USD = mean(USD))

RF.EU <- read_rds("All_years_ready.rds")
RF.EU <- select(RF.EU, c("TIME_PERIOD", "return"))

factors <- read_rds("new_factors_all.rds")
```


# Mean variance
## Function to do the optimization
```{r}
optimize_portfolio <- function(excess_returns, cov_period){
  n_assets <- length(excess_returns)
  
  Dmat <- cov_period
  dvec <- rep(0, n_assets)
  Amat <- cbind(rep(1, n_assets), diag(n_assets))
  bvec <- c(
    1,                   # The value for the first constraint (sum(...) = 1)
    rep(0, n_assets)     # The values for the w_i >= 0 constraints
  )
  meq <- 1
  
  sol<- solve.QP(Dmat = Dmat,
                              dvec = dvec,
                              Amat = Amat,
                              bvec = bvec,
                              meq = meq)
  w <- sol$solution/sum(sol$solution)
  return(w)
}

optimize_internal <- function(excess_returns, cov_period, target_return){
  n_assets <- length(excess_returns)
  
  Dmat <- cov_period
  dvec <- rep(0, n_assets)
  Amat <- cbind(excess_returns, rep(1, n_assets), diag(n_assets))
  bvec <- c(                   # The value for the first constraint (sum(...) = 1)
    target_return,
    1,
    rep(0, n_assets)     # The values for the w_i >= 0 constraints
  )
  meq <- 1
  
  sol<- solve.QP(Dmat = Dmat,
                              dvec = dvec,
                              Amat = Amat,
                              bvec = bvec,
                              meq = meq)
  w <- sol$solution/sum(sol$solution)
  return(w)
}


optimize_return <- function(excess_returns){
  n_assets <- length(excess_returns)
  objective.in <- excess_returns
  const.mat <- matrix(rep(1, n_assets), nrow = 1)
  const.dir <- "=="
  const.rhs <- 1
  
  solution <- lp(
    direction = "max",
    objective.in = objective.in,
    const.mat = const.mat,
    const.dir = const.dir,
    const.rhs = const.rhs
  )
  return(solution$solution)
}

cum_return <- function(x){
  return(
    (cumprod(1+x/100)-1)*100
  )
}

```


<!-- ```{r til opgave b} -->
<!-- optimize_portfolio <- function(excess_returns, cov_period){ -->
<!--   n_assets <- length(excess_returns) -->

<!--   Dmat <- cov_period -->
<!--   dvec <- rep(0, n_assets) -->
<!--   Amat <- cbind(c(1, 0, 0, 1 , 0, 0, 1), c(rep(0, 6), 1)) -->
<!--   bvec <- c( -->
<!--     1,                   # The value for the first constraint (sum(...) = 1) -->
<!--     0     # The values for the w_i >= 0 constraints -->
<!--   ) -->
<!--   meq <- 1 -->

<!--   sol<- solve.QP(Dmat = Dmat, -->
<!--                               dvec = dvec, -->
<!--                               Amat = Amat, -->
<!--                               bvec = bvec, -->
<!--                               meq = meq) -->
<!--   w <- sol$solution/sum(sol$solution) -->
<!--   return(w) -->
<!-- } -->

<!-- optimize_internal2 <- function(excess_returns, cov_period, target_return){ -->
<!--   n_assets <- length(excess_returns) -->

<!--   Dmat <- cov_period -->
<!--   dvec <- rep(0, n_assets) -->
<!--   Amat <- cbind(excess_returns, c(1, 0, 0, 1 , 0, 0, 1), c(rep(0, 6), 1)) -->
<!--   bvec <- c(                   # The value for the first constraint (sum(...) = 1) -->
<!--     target_return, -->
<!--     1, -->
<!--     0     # The values for the w_i >= 0 constraints -->
<!--   ) -->
<!--   meq <- 2 -->

<!--   sol<- solve.QP(Dmat = Dmat, -->
<!--                               dvec = dvec, -->
<!--                               Amat = Amat, -->
<!--                               bvec = bvec, -->
<!--                               meq = meq) -->
<!--   w <- sol$solution -->
<!--   return(w) -->
<!-- } -->

<!-- # t(cbind(1:7, c(1, 0, 0, 1 , 0, 0, 1), c(rep(0, 6), 1))) -->
<!-- # c(                   # The value for the first constraint (sum(...) = 1) -->
<!-- #     1:7, -->
<!-- #     1, -->
<!-- #     0     # The values for the w_i >= 0 constraints -->
<!-- #   ) -->

<!-- optimize_return <- function(excess_returns){ -->
<!--   n_assets <- length(excess_returns) -->
<!--   objective.in <- excess_returns -->
<!--   const.mat <- matrix(c(1, 0, 0, 1, 0, 0, 1, rep(0, n_assets-1), 1), nrow = 2, ncol = 7, byrow = TRUE) -->
<!--   const.dir <- c("==", ">=") -->
<!--   const.rhs <- c(1, 0) -->

<!--   solution <- lp( -->
<!--     direction = "max", -->
<!--     objective.in = objective.in, -->
<!--     const.mat = const.mat, -->
<!--     const.dir = const.dir, -->
<!--     const.rhs = const.rhs -->
<!--   ) -->
<!--   return(solution$solution) -->
<!-- } -->





<!-- ``` -->

## Min variance
```{r}
size_mom_6_EU <- size_mom_6_euro$subsets$data[[1]] %>% filter(date >= 200409 & date <= 202412)

excess_returns_EU <- sweep(size_mom_6_EU[,-1], 1, RF.EU$return, "-") %>% 
  mutate(.before = 1, date = size_mom_6_EU$date)


RF.US <- ff_3_factors$subsets$data[[1]] %>% filter(date >= 200409 & date <= 202412) %>% 
  select(c("date", "RF"))

exchange_rate_US <- select(exchange_rate, c("Date", "USD")) %>% 
  filter(Date >= "2004-09-01" & Date <= "2024-12-31") %>% 
  mutate(Date = floor_date(Date, "month")) %>% 
  group_by(Date) %>% 
  summarise(USD = mean(USD))


size_mom_6_US <- size_mom_6$subsets$data[[1]] %>% filter(date >= 200409 & date <= 202412)
size_mom_6_US[,-1] <- sweep(size_mom_6_EU[,-1], 1, exchange_rate_US$USD, "/")

excess_returns_US <- sweep(size_mom_6_US[,-1], 1, RF.EU$return, "-") %>% 
  mutate(.before = 1, date = size_mom_6_US$date)

excess_returns <- left_join(excess_returns_EU, excess_returns_US, by = "date", suffix = c(".EU", ".US"))


n <- nrow(excess_returns)-35-1
w_matrix3 <- matrix(NA, nrow = n, ncol = 12)

for(i in 1:n){
  returns_period <- excess_returns[i:(i+35),-1]
  mu <- colMeans(returns_period)
  cov_period <- cov(returns_period)
  
  if(all(mu <= 0)){
    w_matrix3[i,] <- 0
  } else{
    w_matrix3[i,] <- optimize_portfolio(mu, cov_period)
  }
}
w_df3 <- as_tibble(w_matrix3)
names(w_df3) <- names(excess_returns[, -1])
w_df3 <- w_df3 %>% 
  mutate(.before = 1, date = size_mom_6_EU$date[36:(nrow(size_mom_6_EU)-1)])
w_df3 <- mutate(w_df3, RF = 1-rowSums(w_df3[,-1]))
round(w_df3, 3)

rowSums(w_df3[,-1])

returns <- left_join(size_mom_6_EU, size_mom_6_US, by = "date", suffix = c(".EU", ".US"))
returns$RF <- RF.EU$return
returns <- returns %>% filter(date >= "200709" & date <= "202412")

return_strat <- round(returns[,-1] * w_df3[,-1], 3)

ggplot(mapping = aes(x = rowSums(return_strat))) + 
  geom_histogram(color = "white") +
  geom_vline(xintercept = quantile(rowSums(return_strat), p = c(0.025, 0.975)))

# mean(rowSums(return_strat))
```

## Max return
```{r}
n <- nrow(excess_returns)-35-1
w_matrix_max_return <- matrix(NA, nrow = n, ncol = 12)

for(i in 1:n){
  returns_period <- excess_returns[i:(i+35),-1]
  mu <- colMeans(returns_period)
  
  
  if(all(mu <= 0)){
    w_matrix_max_return[i,] <- 0
  } else{
    w_matrix_max_return[i,] <- optimize_return(mu)
  }
}

w_max_return <- as_tibble(w_matrix_max_return)
names(w_max_return) <- names(excess_returns[, -1])
w_max_return <- w_max_return %>% 
  mutate(.before = 1, date = size_mom_6_EU$date[36:(nrow(size_mom_6_EU)-1)])
w_max_return <- mutate(w_max_return, RF = 1-rowSums(w_max_return[,-1]))
round(w_max_return, 3)

max_return_strat <- round(returns[,-1] * w_max_return[,-1], 3)
mean(rowSums(max_return_strat[,-1]))

```

## Efficient frontier

<!-- ```{r} -->
<!-- factors_excess_return <- sweep(factors[,-1], 1, RF.EU$return, "-") -->
<!-- factors_excess_return <- cbind(factors$date, factors_excess_return) -->



<!-- n_assets <- ncol(factors_excess_return[,-1]) -->
<!-- n <- nrow(factors_excess_return) - 35 - 1 -->
<!-- w_min_var <- matrix(NA, nrow = n, ncol = n_assets) -->
<!-- w_max_return <- matrix(NA, nrow = n, ncol = n_assets) -->

<!-- n_internal <- 5 -->
<!-- w_internal <- array(NA, dim = c(n_internal, n, n_assets)) -->
<!-- target_returns <- array(NA, c(n, n_internal)) -->
<!-- Sigma <- array(NA, c(n, n_assets, n_assets)) -->
<!-- mu <- array(NA, c(n, n_assets)) -->

<!-- for(i in 1:n){ -->
<!--   excess_returns_period <- factors_excess_return[i:(i+35),-1] -->
<!--   mu[i,] <- colMeans(excess_returns_period) -->
<!--   Sigma[i,,] <- cov(excess_returns_period) -->
<!--   if(all(mu <= 0)){ -->
<!--     w_min_var[i,] <- 0 -->
<!--     w_max_return[i,] <- 0 -->
<!--     w_internal[,i , ] <- 0 -->
<!--     target_returns[i,] <- 0 -->
<!--   } else{ -->
<!--     w_min_var[i,] <- optimize_portfolio(mu[i,], Sigma[i,,]) -->
<!--     w_max_return[i,] <- optimize_return(mu[i,]) -->

<!--     return_min_var <- sum(mu[i,]*w_min_var[i,]) -->
<!--     return_max_return <- sum(mu[i,]*w_max_return[i,]) -->

<!--     target_returns_tmp <- seq(return_min_var, return_max_return, (return_max_return - return_min_var)/(n_internal+1)) -->
<!--     target_returns[i,] <- target_returns_tmp[-c(1, length(target_returns_tmp))] -->
<!--     for(j in 1:length(target_returns[i,])){ -->
<!--       w_internal[j,i,] <- optimize_internal(mu[i,], Sigma[i,,], target_returns[i,j]) -->
<!--     } -->
<!--   } -->
<!-- } -->

<!-- colnames(w_min_var) <- colnames(factors[,-1]) -->
<!-- current_dimnames <- dimnames(w_internal) -->
<!-- current_dimnames[[3]] <- colnames(factors[,-1]) -->
<!-- dimnames(w_internal) <- current_dimnames -->
<!-- colnames(w_max_return) <- colnames(factors[,-1]) -->

<!-- factors_period <- factors[37:nrow(factors),] -->

<!-- return_min_var <- rowSums(w_min_var*factors_period[,-1]) -->
<!-- return_max_return <- rowSums(w_max_return*factors_period[,-1]) -->
<!-- return_internal <- array(NA, c(n, n_internal)) -->
<!-- for(i in 1:n_internal){ -->
<!--   return_internal[,i] <- rowSums(w_internal[i,,]*factors_period[,-1]) -->
<!-- } -->

<!-- rowSums(w_internal[5,,]) -->

<!-- saveRDS(target_returns[,1], file = "target_returns_portfolio_1.rds") -->
<!-- ``` -->

```{r Uden ad hoc}
factors_excess_return <- sweep(factors[,-1], 1, RF.EU$return, "-")
factors_excess_return <- cbind(factors$date, factors_excess_return)


n_assets <- ncol(factors_excess_return[,-1])
n <- nrow(factors_excess_return) - 35 - 1
w_min_var <- matrix(NA, nrow = n, ncol = n_assets)
w_max_return <- matrix(NA, nrow = n, ncol = n_assets)

n_internal <- 5
w_internal <- array(NA, dim = c(n_internal, n, n_assets))
target_returns <- array(NA, c(n, n_internal))
Sigma <- array(NA, c(n, n_assets, n_assets))
mu <- array(NA, c(n, n_assets))

for(i in 1:n){
  excess_returns_period <- factors_excess_return[i:(i+35),-1]
  mu[i,] <- colMeans(excess_returns_period)
  Sigma[i,,] <- cov(excess_returns_period)
    w_min_var[i,] <- optimize_portfolio(mu[i,], Sigma[i,,])
    w_max_return[i,] <- optimize_return(mu[i,])
    
    return_min_var <- sum(mu[i,]*w_min_var[i,])
    return_max_return <- sum(mu[i,]*w_max_return[i,])
    
    target_returns_tmp <- seq(return_min_var, return_max_return, (return_max_return - return_min_var)/(n_internal+1))
    target_returns[i,] <- target_returns_tmp[-c(1, length(target_returns_tmp))]
    for(j in 1:length(target_returns[i,])){
      w_internal[j,i,] <- optimize_internal(mu[i,], Sigma[i,,], target_returns[i,j])
    }
}

colnames(w_min_var) <- colnames(factors[,-1])
current_dimnames <- dimnames(w_internal)
current_dimnames[[3]] <- colnames(factors[,-1])
dimnames(w_internal) <- current_dimnames
colnames(w_max_return) <- colnames(factors[,-1])

factors_period <- factors[37:nrow(factors),]

return_min_var <- rowSums(w_min_var*factors_period[,-1])
return_max_return <- rowSums(w_max_return*factors_period[,-1])
return_internal <- array(NA, c(n, n_internal))
for(i in 1:n_internal){
  return_internal[,i] <- rowSums(w_internal[i,,]*factors_period[,-1])
}


mean(return_max_return)
```


<!-- ```{r Til opgave 1b} -->
<!-- returns_all <- factors %>% filter(date >= 200409 & date <= 202412) -->
<!-- returns_all <- cbind(returns_all, RF.EU %>% filter(TIME_PERIOD >= ym(200409) & TIME_PERIOD <= ym(202501)) %>% select(return)) -->
<!-- target_returns_all <- readRDS("target_returns_portfolio_1.rds")+0.5 -->

<!-- n_assets <- ncol(returns_all[,-1]) -->
<!-- n <- nrow(returns_all) - 35 - 1 -->
<!-- w <- matrix(NA, nrow = n, ncol = n_assets) -->
<!-- Sigma <- array(NA, c(n, n_assets, n_assets)) -->
<!-- mu <- array(NA, c(n, n_assets)) -->

<!-- for(i in 1:n){ -->
<!--   excess_returns_period <- returns_all[i:(i+35),-1] -->
<!--   mu[i,] <- colMeans(excess_returns_period) -->
<!--   Sigma[i,,] <- cov(excess_returns_period) -->
<!--   w[i,] <- optimize_internal2(mu[i,], Sigma[i,,], target_returns_all[i]) -->
<!-- } -->


<!-- colnames(w) <- colnames(returns_all[,-1]) -->
<!-- factors_period <- returns_all[37:nrow(returns_all),] -->
<!-- returns_shorting <- rowSums(w*factors_period[,-1]) -->

<!-- (cumprod(1+returns_shorting/100)-1)*100 -->

<!-- sd(returns_shorting) -->
<!-- ``` -->

## max return target variance
```{r}
# factors ligger i US-US
all_factors <- data.frame(date = factors$date,
                          MKT_US = MKT_EU_US$Mkt[1:244],
                          SMB_US = SMB_EU_US$SMB[1:244],
                          MOM_US = MOM_EU_US$MOM[1:244],
                          MKT_EU = MKT_EU_EU$Mkt[1:244],
                          SMB_EU = SMB_EU_EU$SMB[1:244],
                          MOM_EU = MOM_EU_EU$MOM[1:244],
                          RF = RF.EU$return)
returns_all <- all_factors %>% filter(date >= 200409 & date <= 202412)

cov_period <- cov(returns_all[,-1])
n_assets <- length(colMeans(returns_all[,-1]))
target_variance <- 7 

optimize_b <- function(mean_returns, cov_period, target_variance){
  n_assets <- length(mean_returns)
  
  objective_func <- function(w) {
    portfolio_return <- sum(w * mean_returns)
    return(-portfolio_return) 
  }
  
  equality_constraints <- function(w) {
    #portfolio_var <- t(w) %*% cov_period %*% w
    sum_of_weights <- sum(w[c(1, 4, 7)])
    #return(c(portfolio_var, sum_of_weights))
    return(sum_of_weights)
  }
  
  equality_targets <- c(
    #target_variance, 
    1                
  )
  
  inequality_constraints <- function(w){
    portfolio_var <- t(w) %*% cov_period %*% w
    return(portfolio_var)
  }
  
  inequality_upper <- target_variance
  inequality_lower <- 0
  
  initial_weights <- rep(1 / n_assets, n_assets)
  
  lower_bounds <- c(rep(-5, n_assets-1), 0)
  upper_bounds <- rep(5, n_assets)
  
  sol <- solnp(
    pars = initial_weights,
    fun = objective_func,
    eqfun = equality_constraints,
    eqB = equality_targets,
    ineqfun = inequality_constraints,
    ineqUB = inequality_upper,
    ineqLB = inequality_lower,
    LB = lower_bounds,
    UB = upper_bounds,
    control = list(trace = 0, rho = 1000)
  )
  
  return(sol$pars)
}


optimal_weights <- optimize_b(colMeans(returns_all[,-1]), cov(returns_all[,-1]), 10)
print(round(optimal_weights, 3))
t(optimal_weights)%*%cov_period%*%optimal_weights
```


```{r}
n <- 208
target_variance <- rep(0, n)
for(i in 1:n){
  target_variance[i] <- t(w_internal[1,i,])%*%Sigma[i,,]%*%w_internal[1,i,]
}



n_assets <- ncol(returns_all[,-1])
n <- nrow(returns_all) - 35 - 1
w_b <- matrix(NA, nrow = n, ncol = n_assets)
mu_b <- array(NA, c(n, n_assets))
Sigma_b <- array(NA, c(n, n_assets, n_assets))

for(i in 1:n){
  returns_all_period <- returns_all[i:(i+35),-1]
  mu_b[i,] <- colMeans(returns_all_period)
  Sigma_b[i,,] <- cov(returns_all_period)
  w_b[i,] <- optimize_b(mu_b[i,], Sigma_b[i,,], target_variance[i])
}


colnames(w_b) <- colnames(returns_all[,-1])
factors_period <- returns_all[37:nrow(returns_all),]
returns_shorting <- rowSums(w_b*factors_period[,-1])

(cumprod(1+returns_shorting/100)-1)*100

sd(returns_shorting)

var_short <- rep(NA, 208)
for(i in 1:n){
  var_short[i] <- t(w_b[i,])%*%Sigma_b[i,,]%*%w_b[i,]
}

w_b[190:208,]

sum(round(var_short, 0) != round(target_variance, 0))

var_short >= target_variance

ggplot() +
  geom_point(aes(1:208, var_short), color = "red") +
  geom_point(aes(1:208, target_variance), color = "green")

Sigma_b[1,,]
```

## Target return min variance
```{r}
optimize_target_return_b <- function(returns, cov_period, target_return){
  n_assets <- length(returns)
  
  Dmat <- cov_period
  dvec <- rep(0, n_assets)
  Amat <- cbind(returns, c(1, 0, 0, 1, 0, 0, 1), c(rep(0, 6), 1))
  bvec <- c(                   
    target_return,
    1,      # The value for the first constraint (sum(...) = 1)
    0     # The values for the w_7 >= 0 constraints
  )
  meq <- 2
  
  sol<- solve.QP(Dmat = Dmat,
                              dvec = dvec,
                              Amat = Amat,
                              bvec = bvec,
                              meq = meq)
  w <- sol$solution
  return(w)
}


target_return_b <- target_returns[,1]
n_assets <- ncol(returns_all[,-1])
n <- nrow(returns_all) - 35 - 1
w_b_target_return <- matrix(NA, nrow = n, ncol = n_assets)
mu_b_target_return <- array(NA, c(n, n_assets))
Sigma_b_target_return <- array(NA, c(n, n_assets, n_assets))

for(i in 1:n){
  returns_all_period <- returns_all[i:(i+35),-1]
  mu_b_target_return[i,] <- colMeans(returns_all_period)
  Sigma_b_target_return[i,,] <- cov(returns_all_period)

  w_b_target_return[i,] <- optimize_target_return_b(
    mu_b_target_return[i,],
    Sigma_b_target_return[i,,],
    target_return_b[i]
  )
}

returns_short <- rowSums(w_b_target_return*mu_b_target_return)

ggplot() +
  geom_point(aes(1:n, returns_short), col = "red") +
  geom_point(aes(1:n, rowSums(mu_b_target_return)), col = "green")

w_b_target_return[1:10,]
```


### Plot af efficient frontier
```{r}
var_func <- function(w, Sigma, k){
  return(
    t(w[k,])%*%Sigma[k,,]%*%w[k,]
  )
}

k <- 208

variance_k <- c(var_func(w_min_var, Sigma, k))
for(i in 1:n_internal){
  variance_k <- c(variance_k, var_func(w_internal[i,,], Sigma, k))
}
variance_k <- c(variance_k, var_func(w_max_return, Sigma, k))

# returns 
return_min_var_k <- sum(w_min_var[k,]*mu[k,])
return_max_return_k <- sum(w_max_return[k,]*mu[k,])
return_internal_k <- rep(NA, n_internal)
for(i in 1:n_internal){
  return_internal_k[i] <- sum(w_internal[i,k,]*mu[k,])
}
return_k <- c(return_min_var_k, return_internal_k, return_max_return_k)
return_k

df_frontier <- tibble(
  "variance" = variance_k,
  "Return" = return_k
)

factors[k:(nrow(factors)-1),]

ggplot(df_frontier, aes(variance, Return)) +
  geom_point() +
  ggtitle("Efficient frontier 12-2021 to 11-2024") +
  theme_bw()
```

### Plot of cumulative return
#### min_var max_return
```{r}
k <- n
return_min_var[k]
return_max_return[k]

# return for perioden
cumulative_return_min_var <- (cumprod(1+return_min_var/100)-1)*100
cumulative_return_max_return <- (cumprod(1+return_max_return/100)-1)*100
cumulative_return_market <- (cumprod(1+factors_period$MKT_EU_EU/100)-1)*100

cumulative_return_min_var[k]/n
cumulative_return_max_return[k]/n

sd(return_min_var)
sd(return_max_return)

cumulative_return_df <- tibble(
  "Date" = factors_period$date,
  "Min_var" = cumulative_return_min_var,
  "Max_return" = cumulative_return_max_return,
  "Current_strategy" =  cumulative_return_market
)

cumulative_return_df %>% 
  pivot_longer(cols = -Date, names_to = "Portfolio", values_to = "Cumulated_returns") %>% 
  mutate(Date = ym(Date)) %>% 
  ggplot(aes(Date, Cumulated_returns, color = Portfolio)) +
    geom_line(linewidth = 1) +
    theme_bw() +
    ggtitle("Cumulative returns") +
    ylab("Cumulative returns") +
    scale_color_manual(
      name = "Portfolio Type",
      breaks = c("Max_return", "Min_var", "Current_strategy"),
      labels = c("Maximum Return", "Minimum Variance", "Current strategy"),
      values = c("Max_return" = "#0072B2", "Min_var" = "#D55E00", "Current_strategy" = "#009E73") 
    )


Breaks = c("Max_return", "Min_var", "Current_strategy")
labels = c("Maximum Return", "Minimum Variance", "European equity")
values = c("Max_return" = "#0072B2", "Min_var" = "#D55E00", "Current_strategy" = "#009E73")

cumulative_return_df %>% 
  pivot_longer(cols = -Date, names_to = "Portfolio", values_to = "Cumulative_return") %>% 
  mutate(Date = ym(Date)) %>% 
ggplot(aes(x = Date, y = Cumulative_return, color = Portfolio)) +
  geom_line(linewidth = 1) +
  scale_color_manual(
      name = "Portfolio",
      breaks = Breaks,
      labels = labels,
      values =  values
    ) +
  labs(
    title = "Cumulative Returns",
    #subtitle = "",
    x = "Date",
    y = "Cumulative Return",
    color = "Portfolio"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12),
    legend.position = "right",
    legend.title = element_text(face = "bold")
  )

colorRampPalette(c("#D55E00", "#0072B2"))(7)

```

#### Whole frontier
```{r}
cumulative_return_internal <- array(NA, c(n, n_internal))
for(i in 1:n_internal){
  cumulative_return_internal[,i] <- (cumprod(1+return_internal[,i]/100)-1)*100
}

cumulative_return_df <- data.frame(
  cumulative_return_min_var,
  cumulative_return_internal,
  cumulative_return_max_return,
  cumulative_return_market
)

new_names <- c("Minimum variance", paste("point", 1:5), "Maximum return", "European Equity")

colnames(cumulative_return_df) <- new_names

values <- c(colorRampPalette(c("#D55E00", "#0072B2"))(7), "#009E73")
labels <- c("GMV", paste("Point", 1:5, sep = " "), "Max Return", "EE")

plot_data <- cumulative_return_df %>%
  mutate(Date = ym(factors_period$date)) %>%
  pivot_longer(
    cols = -Date,
    names_to = "Portfolio",
    values_to = "Cumulative_Return"
  ) %>%
  mutate(Portfolio = factor(Portfolio, levels = new_names))

ggplot(plot_data, aes(x = Date, y = Cumulative_Return, color = Portfolio)) +
  geom_line(linewidth = 0.7) +
  scale_color_manual(values = values, labels = labels) +
  labs(
    title = "Cumulative Returns of Efficient Frontier Portfolios",
    #subtitle = "Performance of portfolios from Minimum Variance to Maximum Return",
    x = "Date",
    y = "Cumulative Return",
    color = "Portfolio"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12),
    legend.position = "right",
    legend.title = element_text(face = "bold")
  )



c(min(cumulative_return_internal[k,]), max(cumulative_return_internal[k,]))
c(min(cumulative_return_internal[k,]/n), max(cumulative_return_internal[k,]/n))
c(min(apply(return_internal, 2, sd)), max(apply(return_internal, 2, sd)))

which.max(cumulative_return_internal[k,])
which.min(sd(cumulative_return_internal[k,]))




```

```{r}
library(ggplot2)
library(patchwork)
library(lubridate)
library(dplyr)

# (Assuming 'plot_data', 'values', and 'labels' are in your environment)

# 1. Create your main plot
main_plot <- ggplot(plot_data, aes(x = Date, y = Cumulative_Return, color = Portfolio)) +
  geom_line(linewidth = 0.7) +
  
  # --- ADDED THIS RECTANGLE ---
  # This highlights the area that the inset plot is zooming in on
  annotate(
    "rect",
    xmin = as.Date("2007-09-01"),
    xmax = as.Date("2012-08-01"),
    ymin = -Inf,
    ymax = Inf,
    fill = "grey80", 
    alpha = 0.4
  ) +
  # --- END OF ADDED RECTANGLE ---
  
  scale_color_manual(values = values, labels = labels) +
  labs(
    title = "Cumulative Returns of Efficient Frontier Portfolios",
    #subtitle = "Performance of portfolios from Minimum Variance to Maximum Return",
    x = "Date",
    y = "Cumulative Return",
    color = "Portfolio"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12),
    legend.position = "right",
    legend.title = element_text(face = "bold")
  )

# 2. Filter the data for the inset
plot_data_inset <- plot_data %>%
  filter(Date >= as.Date("2007-09-01") & Date <= as.Date("2012-08-01"))

# 3. Create the inset plot from the filtered data
inset_plot <- ggplot(plot_data_inset, aes(x = Date, y = Cumulative_Return, color = Portfolio)) +
  geom_line(linewidth = 0.7) +
  scale_color_manual(values = values, labels = labels) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.title = element_blank(),
    axis.text = element_text(size = 8),
    plot.title = element_blank(),
    panel.border = element_rect(color = "grey50", fill = NA),
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA)
  )

# 4. Combine the plots
main_plot +
  inset_element(
    inset_plot,
    left = 0.05,
    bottom = 0.50,
    right = 0.55,
    top = 0.95
  )
```

# Risk parity
```{r}
n_factors <- ncol(factors[,-1])
n <- nrow(factors)-35-1
w_matrix_rp <- matrix(NA, nrow = n, ncol = n_factors)

for(i in 1:n){
  factors_period_tmp <- factors[i:(i+35),-1]
  volatility <- (factors_period_tmp %>%
    summarise(across(c(MKT_EU_US, SMB_EU_US, MOM_EU_US, MKT_EU_EU, SMB_EU_EU, MOM_EU_EU), ~sd(.x)))) %>% 
    as.numeric()
  w_matrix_rp[i,] <- 1/volatility/sum(1/volatility)
}

w_rp <- as_tibble(w_matrix_rp)
names(w_rp) <- names(factors[, -1])
w_rp <- w_rp %>% 
  mutate(.before = 1, date = factors$date[37:nrow(factors)])
round(w_rp, 3)

factors_return_calc <- factors[37:nrow(factors),]

return_rp <- rowSums(w_rp[,-1]*factors_return_calc[,-1])

mean(return_rp)
```

## Plot af risk parity
```{r}
k <- 1

cumulative_return_rp <- (cumprod(1+return_rp/100)-1)*100
cumulative_return_mv_chosen <- cumulative_return_internal[,k]

round(cumulative_return_rp[n], 0)-round(cumulative_return_mv_chosen[n], 0)
round(cumulative_return_rp[n]/n, 2) - round(cumulative_return_mv_chosen[n]/n, 2)
round(sd(return_rp), 2)-round(sd(return_internal[,k]), 2)

rp_df <- tibble(
  Date = ym(factors_return_calc$date),
  "Risk_parity" = cumulative_return_rp,
  "Portfolio_1" = cumulative_return_mv_chosen,
  "Current_strategy" =  cumulative_return_market
)

Breaks = c("Risk_parity", "Portfolio_1", "Current_strategy")
labels = c("Risk parity", "Portfolio 1", "European Equity")
values = c("Risk_parity" = "#0072B2", "Portfolio_1" = "#D55E00", "Current_strategy" = "#009E73")

rp_df %>% 
  pivot_longer(cols = -Date, names_to = "Portfolio", values_to = "Cumulative_Return") %>% 
  ggplot(aes(x = Date, y = Cumulative_Return, color = Portfolio)) +
    geom_line(linewidth = 1) +
    scale_color_manual(
        name = "Portfolio",
        breaks = Breaks,
        labels = labels,
        values =  values
      ) +
    labs(
      title = "Cumulative Returns of Risk parity portfolio and Portfolio 1",
      x = "Date",
      y = "Cumulative Return"
    ) +
    theme_minimal() +
    theme(
      plot.title = element_text(face = "bold", size = 16),
      plot.subtitle = element_text(size = 12),
      legend.position = "right",
      legend.title = element_text(face = "bold")
    )

# df <- tibble(date = factors_return_calc$date, return = return_internal[,1])
# saveRDS(df, "returns_choice.rds")


```

```{r}
returns_all <- cbind(
  factors$date,
  return_min_var,
  return_internal,
  return_max_return
) %>% 
  as.tibble()

new_names <- c("date", "min_var", paste("Portfolio ", 1:5), "max_return")

colnames(returns_all) <- new_names

cumulative_returns_all <- returns_all %>% 
  mutate(across(2:8, ~(cumprod(1+.x/100)-1))*100)

summary_table <- cumulative_returns_all %>%
  pivot_longer(cols = -date, names_to = "Portfolio", values_to = "Cumulative_return") %>% 
  mutate(Portfolio = factor(Portfolio, levels = new_names)) %>%
  group_by(Portfolio) %>% 
  summarise(
    "Cumulative_return_end" = last(Cumulative_return),
    "Mean_return" = Cumulative_return_end/n
  )

volatility <- returns_all %>% 
  pivot_longer(cols = -date, names_to = "Portfolio", values_to = "Returns") %>% 
  mutate(Portfolio = factor(Portfolio, levels = new_names)) %>%
  group_by(Portfolio) %>% 
  summarise(Volatility = sd(Returns))

summary_table <- left_join(summary_table, volatility, by = "Portfolio")
summary_table <- rbind(summary_table, tibble(
  Portfolio = "Risk_parity",
  Cumulative_return_end = cumulative_return_rp[n],
  Mean_return = cumulative_return_rp[n]/n,
  Volatility = sd(return_rp)
))






returns_choice <- tibble(
  date = returns_all$date,
  "return" = returns_all$`Portfolio  2`
)

```

```{r}
k <- 1

cumulative_return_rp <- (cumprod(1+return_rp/100)-1)*100
cumulative_return_mv_chosen <- cumulative_return_internal[,k]

round(cumulative_return_rp[n], 0)-round(cumulative_return_mv_chosen[n], 0)
round(cumulative_return_rp[n]/n, 2) - round(cumulative_return_mv_chosen[n]/n, 2)
round(sd(return_rp), 2)-round(sd(return_internal[,k]), 2)

mkt_EU_period <- filter(factors, date >= 200709& date <= 202412) %>% select(c("date", "MKT_EU_EU"))

cumulative_return_market <- (cumprod(1+mkt_EU_period$MKT_EU_EU/100)-1)*100

rp_df <- tibble(
  Date = ym(factors_return_calc$date),
  "Risk parity" = cumulative_return_rp,
  "Portfolio 1" = cumulative_return_mv_chosen,
  "EU equity" = cumulative_return_market
)


rp_df %>% 
  pivot_longer(cols = -Date, names_to = "Portfolio", values_to = "Cumulative_Return") %>% 
  ggplot(aes(x = Date, y = Cumulative_Return, color = Portfolio)) +
    geom_line(linewidth = 1) +
    labs(
      title = "Cumulative Returns of Risk parity portfolio and Portfolio 1",
      x = "Date",
      y = "Cumulative Return"
    ) +
    theme_minimal() +
    theme(
      plot.title = element_text(face = "bold", size = 16),
      plot.subtitle = element_text(size = 12),
      legend.position = "right",
      legend.title = element_text(face = "bold")
    )

sd(factors_period$MKT_EU_EU)
```

# With shorting
## Factors
```{r}
all_factors <- data.frame(date = factors$date,
                          MKT_US = MKT_EU_US$Mkt[1:244],
                          SMB_US = SMB_EU_US$SMB[1:244],
                          MOM_US = MOM_EU_US$MOM[1:244],
                          MKT_EU = MKT_EU_EU$Mkt[1:244],
                          SMB_EU = SMB_EU_EU$SMB[1:244],
                          MOM_EU = MOM_EU_EU$MOM[1:244],
                          RF = RF.EU$return)
returns_all <- all_factors %>% filter(date >= 200409 & date <= 202412)
```
## Optimization
```{r}
optimize_with_shorting <- function(alpha, returns){
  
  returns_tmp <- returns %>% 
    select(-RF)
  
  factor_names <- colnames(returns_tmp[,-1])
  
  n_assets <- ncol(returns_tmp[,-1])
  n <- nrow(returns_tmp) - 35 - 1
  w_min_var <- matrix(NA, nrow = n, ncol = n_assets)
  w_max_return <- matrix(NA, nrow = n, ncol = n_assets)
  
  n_internal <- 5
  w_internal <- array(NA, dim = c(n_internal, n, n_assets))
  target_returns <- array(NA, c(n, n_internal))
  Sigma <- array(NA, c(n, n_assets, n_assets))
  mu <- array(NA, c(n, n_assets))
  
  for(i in 1:n){
    returns_period <- returns_tmp[i:(i+35),-1]
    mu[i,] <- colMeans(returns_period)
    Sigma[i,,] <- cov(returns_period)
      w_min_var[i,] <- optimize_portfolio(mu[i,], Sigma[i,,])
      w_max_return[i,] <- optimize_return(mu[i,])
      
      return_min_var <- sum(mu[i,]*w_min_var[i,])
      return_max_return <- sum(mu[i,]*w_max_return[i,])
      
      target_returns_tmp <- seq(return_min_var, return_max_return, (return_max_return - return_min_var)/(n_internal+1))
      target_returns[i,] <- target_returns_tmp[-c(1, length(target_returns_tmp))]
      for(j in 1:length(target_returns[i,])){
        w_internal[j,i,] <- optimize_internal(mu[i,], Sigma[i,,], target_returns[i,j])
      }
  }
  w = array(NA, c(7, dim(w_min_var)[1], dim(w_min_var)[2]))
  w[1,,] <- w_min_var
  w[2:6,,] <- w_internal
  w[7,,] <- w_max_return
  
  
  current_dimnames <- dimnames(w)
  current_dimnames[[3]] <- factor_names
  dimnames(w) <- current_dimnames
  
  factors_out_of_bag <- returns[37:nrow(returns),]
  returns_out_of_bag <- returns_in_bag <-array(NA, c(n, dim(w)[[1]]))
  
  for(i in 1:dim(w)[[1]]){
    returns_out_of_bag[,i] <- 1/alpha*rowSums(w[i,,]*factors_out_of_bag[,2:7]) + alpha*(1-rowSums(w[i,,c("SMB_US","MOM_US", "SMB_EU", "MOM_EU")]))*factors_out_of_bag[,"RF"]
    
    returns_in_bag[,i] <- 1/alpha*rowSums(w[i,,]*mu) + alpha*(1-rowSums(w[i,,c("SMB_US","MOM_US", "SMB_EU", "MOM_EU")]))*returns[36:(nrow(returns)-1),"RF"]
  }
  
  w_scaled <- w
  
  w_scaled[,,c("SMB_US","MOM_US", "SMB_EU", "MOM_EU")] <- w_scaled[,,c("SMB_US","MOM_US", "SMB_EU", "MOM_EU")]*1/alpha
  
  return(
    list(
      "w" = w,
      "w_scaled" = w_scaled,
      "returns_in_bag" = returns_in_bag,
      "returns_out_of_bag" = returns_out_of_bag,
      "Sigma" = Sigma
    )
  )
}


h <- optimize_with_shorting(1/2, returns_all)

apply(h$returns_out_of_bag, 2, cum_return)[208,]

var_short <- rep(NA, 208)
for(i in 1:208){
  var_short[i] <- t(h$w_scaled[2,i,])%*%h$Sigma[i,,]%*%h$w_scaled[2,i,]
}

mean(var_short)
```


