---
title: "USA-USA"
author: "Andreas Fleischer"
date: "2025-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pakker
```{r}
library(readr)
library(tidyverse)
library(frenchdata)
library(ggplot2)
library(lubridate)
```

# Data
```{r message=FALSE, warning=FALSE}
data_sets = get_french_data_list() # All the datasets in the package


# US stocks
# Nr 1 er månedlige returns
# Nr 2 er årlige returns
ff_3_factors <- download_french_data("Fama/French 3 Factors") # Download of data
# f_3_factors$subsets$data[[2]] # How to extract dataset
# browse_details_page(ff_3_factors) # Details of the dataset


size_mom_6 <- download_french_data("6 Portfolios Formed on Size and Momentum (2 x 3)")
size_mom_25 <- download_french_data("25 Portfolios Formed on Size and Momentum (5 x 5)")


# EU stocks in US dollars
size_mom_6_euro <- download_french_data("6 European Portfolios Formed on Size and Momentum (2 x 3)")
size_mom_25_euro <- download_french_data("25 European Portfolios Formed on Size and Momentum (5 x 5)")

# Other
setwd("/Users/andreas/Documents/Uni/5. År/Asset Allocation (PUK)")
exchange_rate <- read_csv("GitHub/AssetAllocation/Data AA/eurofxref-hist.csv") # Tror det er valutakurser
# Yield_curve_1_year <- read_csv("Data AA/Yield curve 1 year.csv")
# Yield_curve <- read_csv("Data AA/Yield curve full.csv")
```

# US-US (MKT)
```{r}
true_factors <- ff_3_factors$subsets$data[[1]] %>% filter(date >= 200409)
avg_vw_returns <- size_mom_6$subsets$data[[1]] %>% filter(date >= 200409)
number_firms <- size_mom_6$subsets$data[[5]] %>% filter(date >= 200409)
avg_market_cap <- size_mom_6$subsets$data[[6]] %>% filter(date >= 200409)

total_returns <- data.frame(date = number_firms$date,
                            avg_vw_returns[,-1]*number_firms[,-1]*avg_market_cap[-1]*1/100)
total_values <- data.frame(date = number_firms$date,
                            number_firms[,-1]*avg_market_cap[-1])
total_market_value <- rowSums(total_values[,-1])
MKT_US <- data.frame(date = number_firms$date,
                     Mkt = rowSums(avg_vw_returns[,-1]*total_values[,-1])/total_market_value)

true_factors$`Mkt-RF`-round(MKT_US$Mkt,2)

summary(lm((MKT_US$Mkt[1:244]-true_factors$RF[1:244])~1))$coefficients*c(1,sqrt(244),1,1)
```
# US-US (SMB)
```{r}
SMB_values <- rowMeans(avg_vw_returns[, 2:4]) - rowMeans(avg_vw_returns[, 5:7])
SMB_US <- data.frame(date = number_firms$date,
                     SMB = SMB_values)

SMB_US$SMB-true_factors$SMB
summary(lm(SMB_US$SMB[1:244]~1))$coefficients*c(1,sqrt(244),1,1)
```
# US-US (MOM)
```{r}
MOM_values <- rowMeans(avg_vw_returns[,c(4,7)]) - rowMeans(avg_vw_returns[,c(2,5)])
MOM_US <- data.frame(date = number_firms$date,
                     MOM = MOM_values)

summary(lm(MOM_US$MOM[1:244]~1))$coefficients*c(1,sqrt(244),1,1)
```

# EUR-US (MKT)
```{r}
EUR_USD <- exchange_rate %>%
  filter(as.Date(Date) >= as.Date("2004-08-01")) %>%
  select(Date, USD) %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(year = year(Date), month = month(Date)) %>%
  slice_max(Date, n = 1) %>%   # last date in each month
  ungroup() %>%
  arrange(Date)
EUR_USD <- EUR_USD[1:253,]
EUR_USD$return <- lag(EUR_USD$USD)/EUR_USD$USD-1
EUR_USD <- EUR_USD[2:253,]

avg_vw_returns_eu <- (1+avg_vw_returns[,-1]/100)*(1+EUR_USD$return)-1
avg_vw_returns_eu <- avg_vw_returns_eu*100

total_values <- number_firms[,-1] * avg_market_cap[,-1]  
total_market_value <- rowSums(total_values)

total_returns_eu <- data.frame(
  date = number_firms$date,
  avg_vw_returns_eu * total_values / 100)

MKT_EU_US <- data.frame(
  date = number_firms$date,
  Mkt = rowSums(avg_vw_returns_eu * total_values) / total_market_value)

t.test(MKT_EU_US$Mkt)
summary(lm(MKT_EU_US$Mkt[1:244]~1))$coefficients*c(1,sqrt(244),1,1)
```
# EUR-US (SMB)
```{r}
SMB_values_eu <- rowMeans(avg_vw_returns_eu[, 1:3]) - rowMeans(avg_vw_returns_eu[, 4:6])
SMB_EU_US <- data.frame(date = number_firms$date,
                     SMB = SMB_values_eu)
t.test(SMB_EU_US$SMB)
summary(lm(SMB_EU_US$SMB[1:244]~1))$coefficients*c(1,sqrt(244),1,1)
```
# EUR-US (MOM)
```{r}
MOM_values_eu <- rowMeans(avg_vw_returns_eu[,c(3,6)]) - rowMeans(avg_vw_returns_eu[,c(1,4)])
MOM_EU_US <- data.frame(date = number_firms$date,
                     MOM = MOM_values_eu)

t.test(MOM_EU_US$MOM)
summary(lm(MOM_EU_US$MOM[1:244]~1))$coefficients*c(1,sqrt(244),1,1)
```
# EUR-EU
```{r}
avg_vw_returns_euro <- size_mom_6_euro$subsets$data[[1]] %>% filter(date >= 200409)
number_firms_euro <- size_mom_6_euro$subsets$data[[5]] %>% filter(date >= 200409)
avg_market_cap_euro <- size_mom_6_euro$subsets$data[[6]] %>% filter(date >= 200409)

total_values_euro <- number_firms_euro[,-1] * avg_market_cap_euro[,-1]
total_market_value_euro <- rowSums(total_values_euro)

avg_vw_returns_euro_eur <- ((1 + avg_vw_returns_euro[,-1]/100) * (1 + EUR_USD$return) - 1) * 100

MKT_EU_EU <- data.frame(
  date = number_firms_euro$date,  
  Mkt  = rowSums(avg_vw_returns_euro_eur * total_values_euro) /
         total_market_value_euro)
t.test(MKT_EU_EU$Mkt)
summary(lm(MKT_EU_EU$Mkt[1:244]~1))$coefficients*c(1,sqrt(244),1,1)
```
# EUR-EU (SMB)
```{r}
SMB_values_eur_eur <- rowMeans(avg_vw_returns_euro_eur[, 1:3]) - 
                      rowMeans(avg_vw_returns_euro_eur[, 4:6])

SMB_EU_EU <- data.frame(
  date = number_firms_euro$date,  
  SMB  = SMB_values_eur_eur
)
t.test(SMB_EU_EU$SMB)
summary(lm(SMB_EU_EU$SMB[1:244]~1))$coefficients*c(1,sqrt(244),1,1)
```
# EUR-EU (MOM)
```{r}
MOM_values_eur_eur <- rowMeans(avg_vw_returns_euro_eur[, c(3,6)]) -
                      rowMeans(avg_vw_returns_euro_eur[, c(1,4)])

MOM_EU_EU <- data.frame(
  date = number_firms_euro$date,  
  MOM  = MOM_values_eur_eur
)

t.test(MOM_EU_EU$MOM)
summary(lm(MOM_EU_EU$MOM[1:244]~1))$coefficients*c(1,sqrt(244),1,1)
```
# Time-series regression (US-US)
```{r}
All_years <- readRDS("All_years_ready.rds")

# Make new FF factor df
RF <- ff_3_factors$subsets$data[[1]] %>% filter(date >= 200409) %>% select(c("RF"))
reg_data_us <- data.frame(
  date = MKT_US$date,
  MKTmRF = MKT_US$Mkt,
  SMB = SMB_US$SMB,
  MOM = MOM_US$MOM) %>%
  filter(date <= 202412) %>%
  mutate(MKTmRF = MKTmRF - RF$RF[1:244],
         RF = RF$RF[1:244])

# Add the portfolios
reg_data_us <- cbind(
  reg_data_us,
  avg_vw_returns[1:244,])

# Excess portfolios, R-RF
excess_portfolios_us <- avg_vw_returns[1:244,-1] - reg_data_us$RF

# Regressions for each portfolio
summary(lm(excess_portfolios_us[,1]~reg_data_us$MKTmRF+reg_data_us$SMB+reg_data_us$MOM))
summary(lm(excess_portfolios_us[,2]~reg_data_us$MKTmRF+reg_data_us$SMB+reg_data_us$MOM))
summary(lm(excess_portfolios_us[,3]~reg_data_us$MKTmRF+reg_data_us$SMB+reg_data_us$MOM))
summary(lm(excess_portfolios_us[,4]~reg_data_us$MKTmRF+reg_data_us$SMB+reg_data_us$MOM))
summary(lm(excess_portfolios_us[,5]~reg_data_us$MKTmRF+reg_data_us$SMB+reg_data_us$MOM))
summary(lm(excess_portfolios_us[,6]~reg_data_us$MKTmRF+reg_data_us$SMB+reg_data_us$MOM))
```

# Time-series regression on 5x5 (EU-US)
```{r}
# Make new FF factor df
reg_data_us <- data.frame(
  date = MKT_EU_US$date,
  MKTmRF = MKT_EU_US$Mkt,
  SMB = SMB_EU_US$SMB,
  MOM = MOM_EU_US$MOM) %>%
  filter(date <= 202412) %>%
  mutate(MKTmRF = MKTmRF - All_years$return,
         RF = All_years$return)
# Add the 5x5 data
avg_vw_returns_eu25 <- size_mom_25$subsets$data[[1]] %>% filter(date >= 200409)
avg_vw_returns_eu25 <- (1+avg_vw_returns_eu25[,-1]/100)*(1+EUR_USD$return)-1
avg_vw_returns_eu25 <- avg_vw_returns_eu25*100

# Add the portfolios
reg_data_us <- cbind(
  reg_data_us,
  avg_vw_returns_eu25[1:244,])

# Excess portfolios, R-RF
excess_portfolios_us <- avg_vw_returns_eu25[1:244,] - reg_data_us$RF

# The regressions
ff25_results <- map_dfr(
  names(excess_portfolios_us),
  ~ {
    model <- lm(excess_portfolios_us[[.x]] ~ reg_data_us$MKTmRF + reg_data_us$SMB + reg_data_us$MOM)
    tidy(model) %>%
      mutate(
        Portfolio = .x,
        t_stat = estimate / std.error
      ) %>%
      select(Portfolio, term, estimate, t_stat)
  }
)

# Arrange nicely
ff25_results <- ff25_results %>%
  mutate(term = recode(term,
                       "(Intercept)" = "Alpha",
                       "reg_data_eu$MKTmRF" = "MKT",
                       "reg_data_eu$SMB" = "SMB",
                       "reg_data_eu$MOM" = "MOM")) %>%
  arrange(Portfolio, match(term, c("Alpha", "MKT", "SMB", "MOM")))

# (Optional) Pivot wider for a report-style table
ff25_table <- ff25_results %>%
  tidyr::pivot_wider(
    names_from = term,
    values_from = c(estimate, t_stat),
    names_glue = "{term}_{.value}"
  )

# View results
ff25_table
```


# Time-series regression (EU-EU)
```{r}
# Make new FF factor df
reg_data_eu <- data.frame(
  date = MKT_EU_EU$date,
  MKTmRF = MKT_EU_EU$Mkt,
  SMB = SMB_EU_EU$SMB,
  MOM = MOM_EU_EU$MOM) %>%
  filter(date <= 202412) %>%
  mutate(MKTmRF = MKTmRF - All_years$return,
         RF = All_years$return)

# Add the 5x5 data
avg_vw_returns_eu25 <- size_mom_25_euro$subsets$data[[1]] %>% filter(date >= 200409)
avg_vw_returns_eu25 <- (1+avg_vw_returns_eu25[,-1]/100)*(1+EUR_USD$return)-1
avg_vw_returns_eu25 <- avg_vw_returns_eu25*100

# Add the portfolios
reg_data_eu <- cbind(
  reg_data_eu,
  avg_vw_returns_eu25[1:244,])

# Excess portfolios, R-RF
excess_portfolios_eu <- avg_vw_returns_eu25[1:244,] - reg_data_eu$RF

# The regressions
ff25_results <- map_dfr(
  names(excess_portfolios_eu),
  ~ {
    model <- lm(excess_portfolios_eu[[.x]] ~ reg_data_eu$MKTmRF + reg_data_eu$SMB + reg_data_eu$MOM)
    tidy(model) %>%
      mutate(
        Portfolio = .x,
        t_stat = estimate / std.error
      ) %>%
      select(Portfolio, term, estimate, t_stat)
  }
)

# Arrange nicely
ff25_results <- ff25_results %>%
  mutate(term = recode(term,
                       "(Intercept)" = "Alpha",
                       "reg_data_eu$MKTmRF" = "MKT",
                       "reg_data_eu$SMB" = "SMB",
                       "reg_data_eu$MOM" = "MOM")) %>%
  arrange(Portfolio, match(term, c("Alpha", "MKT", "SMB", "MOM")))

# (Optional) Pivot wider for a report-style table
ff25_table <- ff25_results %>%
  tidyr::pivot_wider(
    names_from = term,
    values_from = c(estimate, t_stat),
    names_glue = "{term}_{.value}"
  )

# View results
ff25_table

```

